// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV6VdU81BvoRDnxDPqnfeCN9BRvon9-YA',
    appId: '1:568639907795:web:ee95fc2c00e9869958f126',
    messagingSenderId: '568639907795',
    projectId: 'crm-cstone',
    authDomain: 'crm-cstone.firebaseapp.com',
    storageBucket: 'crm-cstone.appspot.com',
    measurementId: 'G-YTDTX8VY9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqfFY347-a8ClWrVbFKZS8q529SqBVn68',
    appId: '1:568639907795:android:87aa2dad71aa264f58f126',
    messagingSenderId: '568639907795',
    projectId: 'crm-cstone',
    storageBucket: 'crm-cstone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuh5xcNI-u_dw8thEH24a8QYaa-eRw-Fo',
    appId: '1:568639907795:ios:a7a210dc291f275958f126',
    messagingSenderId: '568639907795',
    projectId: 'crm-cstone',
    storageBucket: 'crm-cstone.appspot.com',
    androidClientId: '568639907795-k28f9mnk1orgsbbh9sb743thkknvmule.apps.googleusercontent.com',
    iosClientId: '568639907795-m8s77v1mru38lur4po4ap3hvsesduitb.apps.googleusercontent.com',
    iosBundleId: 'com.example.crmMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuh5xcNI-u_dw8thEH24a8QYaa-eRw-Fo',
    appId: '1:568639907795:ios:a7a210dc291f275958f126',
    messagingSenderId: '568639907795',
    projectId: 'crm-cstone',
    storageBucket: 'crm-cstone.appspot.com',
    androidClientId: '568639907795-k28f9mnk1orgsbbh9sb743thkknvmule.apps.googleusercontent.com',
    iosClientId: '568639907795-m8s77v1mru38lur4po4ap3hvsesduitb.apps.googleusercontent.com',
    iosBundleId: 'com.example.crmMobile',
  );
}
